frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Book;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\data\Pagination;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [

            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex($page = 1, $limit = 1)
    {

        $query = Book::find();
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => $limit, 'pageSizeParam' => false]);
        $books = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('index', compact('books', 'pages', 'limit', 'page'));
    }

    public function actionBook($id) {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

use common\models\Book;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $books Book[] */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <?php Pjax::begin(['id' => 'cont-pj']); ?>
    <?php if (!empty($books)) {?>
    <div class="row">
        <?php  foreach ($books as $key => $book) { ?>
            <div class="col-3">
                <div class="book-cart">
                    <?php if (!empty($book->image) && file_exists(Yii::getAlias('@frontend').'/web/'.$book->image)) { ?>
                        <img class="book-cart__cover" src="<?= Yii::$app->request->baseUrl . $book->image ?>" alt="" >
                    <?php } else { ?>
                        <img class="book-cart__cover book-cart__cover--empty" src="" alt="" >
                    <?php } ?>

                    <h2 class="book-cart__title"><?= $book->name ?></h2>
                    <p class="book-cart__genres"><?= \implode(', ', \yii\helpers\ArrayHelper::map($book->getAllGenres(), 'name', 'name')) ?></p>
                    <?= \yii\helpers\Html::a('Подробнее', ['site/book', 'id' => $book->id], ['class' => 'book-cart__link btn btn-primary']) ?>

                </div>
            </div>
        <?php } ?>
    </div>

    <?= Html::hiddenInput('page', $page ?? 0, ['id' => 'page']) ?>
    <?= Html::label( 'Page size:', 'pagesize', array( 'style' => 'margin-left:10px; margin-top:8px;' ) ) ?>
    <?= Html::dropDownList('limit', $limit ?? 0,
            [ 16 => 16, 32 => 32, 48 => 48],
            ['id' => 'spjax']
    );
    ?>

        <?php
        $this->registerJs("
            $(function(){
              $('#spjax').on('change', function(){
                var Id = $(this).val();
                var page = $('#page').val();
              
                $.pjax.reload({
                    container: \"#cont-pj\",
                    url: '/',
                    timeout: 0,
                    data: {
                       'limit': Id ,
                       'page' : page 
                    },
                });
              })  
            })    
            ", View::POS_END)
        ?>

    <?= \yii\widgets\LinkPager::widget([
            'pagination' => $pages,

        ]);

        Pjax::end();
    } ?>

</div>

frontend/views/site/view.php
<?php

use common\models\Book;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Book */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => $model->name];
\yii\web\YiiAsset::register($this);
?>
<div class="author-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            [
                'attribute' => 'image',
                'format' => 'raw',
                'value' => function($model) {
                    /** @var $model Book */
                    return Html::img(Yii::$app->request->baseUrl . $model->image, [
                            'width' => '150'
                    ]);
                }
            ],
            [
                'attribute' => 'public_at',
                'format' => 'raw',
                'value' => function($model) {
                    /** @var $model Book */
                    return $model->getFormattedPublicAt();
                }
            ],
            [
                'attribute' => 'authors',
                'label' => 'Авторы',
                'format' => 'raw',
                'value' => function($model) {
                     /** @var $model Book */
                     return implode(', ', \yii\helpers\ArrayHelper::map($model->getAllAuthors(), 'id', function (\common\models\Author $author) {
                         return $author->getFullName();
                     }));
                }
            ],
            [
                'attribute' => 'genres',
                'label' => 'Жанры',
                'format' => 'raw',
                'value' => function($model) {
                    /** @var $model Book */
                    return implode(', ', \yii\helpers\ArrayHelper::map($model->getAllGenres(), 'id', 'name'));
                }
            ]
        ],
    ]) ?>

</div>